---
- name: "Add Iptables Configuration"
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Install iptables
      package:
        name:
          - iptables
        state: present
    - name: Install cron
      package:
        name:
          - cron
        state: present
      when:
        - ansible_os_family == 'Debian'
    - name: Install cronie
      package:
        name:
          - cronie
        state: present
      when:
        - ansible_os_family == 'RedHat'
    - name: Create scripts directory if it does not exist
      file:
        path: $HOME/deployment/scripts
        state: directory
        mode: u=rw,g=r,o=r
    - name: Copy routing iptables script
      template:
        src: ../templates/routing-iptables.sh.j2
        dest: $HOME/deployment/scripts/routing-iptables.sh
        mode: '+rx'
    - name: Creates cronjob entry for routing table script
      cron:
        name: "a job for routing table script"
        special_time: reboot
        job: "$HOME/deployment/scripts/routing-iptables.sh"
    - name: Run script
      shell: $HOME/deployment/scripts/routing-iptables.sh
